apps/formTest/urls.py
from django.urls import path
import apps.formTest.views as views

urlpatterns = [
    path('form1', views.formTest),
    path('form0', views.form0),
    path('form2', views.form2),
    path('form3', views.form3),
    path('form4', views.form4),
    path('form5', views.form5),
    path('form6', views.form6),
    path('form7', views.form7),
    path('index2/', views.index,name="post_index"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
      path("admin/", admin.site.urls),
      path('', include('apps.mainapp.urls')),
      path('blog/', include('apps.blog.urls')),
      path('forms/', include('apps.formTest.urls')),
      path('viewtest/',include('apps.viewtest.urls')),
      path('blog2/',include('apps.blog2.urls')),
      path('cookietest/',include('apps.cookietest.urls'),name="redirect"),
      path('sessiontest/',include('apps.sessiontest.urls')),
      path('ajaxtest/',include('apps.ajaxtest.urls')),
      path('api/',include('apps.apiTestApp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "پنل مدیریت فروشگاه"
admin.site.index_title = "به پنل مدیریت خوش آمدید"

apps/formTest/models.py
from django.db import models


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان پست ")
    description = models.TextField(max_length=3000, verbose_name="توضیحات")
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.title + " "+self.description

apps/formTest/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.core import validators
from .models import Post


class InputForm0(forms.Form):
    name = forms.CharField(max_length=10, required=True, label="نام")
    family = forms.CharField(max_length=15, label="نام خانوادگی")
    age = forms.IntegerField(label="سن", label_suffix="=>")
    is_active = forms.BooleanField(initial=True)


# ------------------------------------------------------------------------------

class InputForm2(forms.Form):
    name = forms.CharField(max_length=10, required=True, label="نام")
    family = forms.CharField(max_length=15, label="نام خانوادگی")
    age = forms.IntegerField(label="سن", label_suffix="=>")
    is_active = forms.BooleanField(initial=True, label="فعال/غیرفعال")
    avg = forms.DecimalField(max_digits=2, decimal_places=2, label="معدل")
    email = forms.EmailField(max_length=30, label="ایمیل")
    register_date = forms.DateField(label="تاریخ تولد")
    url = forms.URLField(label="آدرس سایت", required=False, initial="http://")
    image = forms.ImageField(label="تصویر", required=False)
    FAVORITS_COLOR = [
        ("1", "RED"),
        ("2", "Blue"),
        ("3", "Green"),
        ("4", "Gray"),
        ("5", "Black")
    ]
    color = forms.ChoiceField(choices=FAVORITS_COLOR, label="رنگ مورد علاقه")


# ------------------------------------------------------------------------------
class InputForm3(forms.Form):
    name = forms.CharField(
        max_length=10,
        required=True,
        label="نام ",
        widget=forms.TextInput(attrs={"class": "c1", "placeholder": "نام را وارد کنید"}))
    family = forms.CharField(
        max_length=15,
        label="نام خانوادگی",
        widget=forms.TextInput(attrs={"class": "c1", "placeholder": "نام خانوادگی را وارد کنید"}))
    password = forms.CharField(
        max_length=100,
        label="رمز عبور",
        widget=forms.PasswordInput(attrs={"class": "c1", "placeholder": "رمز را وارد کنید"}))
    Year_Choies = ["2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", ]
    register_date1 = forms.DateField(label="تاریخ تولد", widget=forms.SelectDateWidget(years=Year_Choies))
    register_date2 = forms.DateField(label="تاریخ تولد", initial=datetime.date.today,
                                     widget=forms.NumberInput(attrs={'type': 'date'}))
    FAVORITS_COLOR = [
        ("1", "RED"),
        ("2", "Blue"),
        ("3", "Green"),
        ("4", "Gray"),
        ("5", "Black")
    ]
    colors1 = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=FAVORITS_COLOR)
    colors2 = forms.ChoiceField(widget=forms.RadioSelect, choices=FAVORITS_COLOR)
    description = forms.BooleanField(widget=forms.Textarea)
    description.widget.attrs.update({"class": "c1"})


# ------------------------------------------------------------------------------
def checkValidateName(value):
    value = str(value)
    if len(value) < 3 or len(value) > 8:
        raise forms.ValidationError("اسم درست نیست")


# def checkValidateage(value):
#     value = int(value)
#     if value<20 or value>40:
#         raise forms.ValidationError("خارج از رده انتخاب شده")


class InputForm4(forms.Form):
    name = forms.CharField(max_length=10, required=True, label="نام", validators=[checkValidateName])
    family = forms.CharField(max_length=15, label="نام خانوادگی")
    age = forms.IntegerField(label="سن",
                             validators=[validators.MaxValueValidator(40, message="سن نیمتواند بیشتر از 40 باشد"),
                                         validators.MinValueValidator(20, message="سن نمیتواند کمتر از 20 باشد")])
    is_active = forms.BooleanField(initial=True, label='فعال/غیرفعال')
    #
    # def clean_name(self):
    #     name = self.cleaned_data["name"]
    #     return name

    # def clean_family(self):
    #     family = self.cleaned_data["family"]
    #     if family[0] != 'A':
    #         raise ValidationError("نام خانوادگی با A شروع نشده است ")
    #     return family
    #
    # def clean_age(self):
    #     age = self.cleaned_data["age"]
    #     return age


class InputForm6(forms.Form):
    name = forms.CharField(max_length=30, label="نام")
    age = forms.IntegerField(label="سن")

    def clean_age(self):
        name = self.cleaned_data["name"]
        if name[0] != 'A':
            raise ValidationError("نام خانوادگی با A شروع نشده است ")
        return name


class InputForm7(forms.ModelForm):
    class Meta :
        model = Post
        fields = "__all__"

apps/formTest/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from .forms import InputForm0, InputForm2, InputForm3, InputForm4, InputForm6, InputForm7
from django.forms import formset_factory
from .models import Post
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here.

def formTest(request):
    content = {
        "media_url": settings.MEDIA_URL,
    }
    return render(request, 'formTest/form1.html', content)


def form0(request):
    form = InputForm0()
    context = {
        "media_url": settings.MEDIA_URL,
        'form': form
    }
    return render(request, "formTest/form0.html", context)


def form2(request):
    form = InputForm2()
    context = {
        "media_url": settings.MEDIA_URL,
        'form': form
    }
    return render(request, "formTest/form2.html", context)


def form3(request):
    form = InputForm2()
    context = {
        "media_url": settings.MEDIA_URL,
        'form': form
    }
    return render(request, "formTest/form3.html", context)


def form4(request):
    form = InputForm3()
    context = {
        "media_url": settings.MEDIA_URL,
        'form': form
    }
    return render(request, "formTest/form4.html", context)


def form5(request):
    form = InputForm4()
    context = {
        "media_url": settings.MEDIA_URL,
    }
    if request.method == "POST":
        form = InputForm4(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data['name'], data['family'], data['age'], data['is_active'])
        else:
            context['error_message'] = 'اطلاعات فرم معتبر نمی باشد'
    else:
        form = InputForm4()

    context['form'] = form
    return render(request, "formTest/form5.html", context)


def form6(request):
    forms_set = formset_factory(InputForm6, extra=3)
    context = {
        'forms_set': forms_set,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, 'formTest/form6.html', context)


def form7(request):
    context = {}
    form = InputForm7(request.POST)
    if form.is_valid():
        data = form.cleaned_data
        post = Post()
        post.title = data['title']
        post.description = data['description']
        post.is_active = data['is_active']
        post.save()
        # return redirect("index2/")
        return HttpResponseRedirect(reverse('post_index'))
    context = {
        "media_url": settings.MEDIA_URL,
        'form': form
    }
    return render(request, 'formTest/form7.html', context)


def index(request):
    posts = Post.objects.all()
    context={
        "posts" : posts
    }
    return render(request,"formTest/index.html",context)

templates/formTest/form0.html
{% extends 'maintemplate.html' %}

{% block content %}
    <h4 class="blog-title"> آموزش کار با فرمها</h4>
    <div class="form-box">
<!--        <form action="">-->
<!--            {% csrf_token %}-->
<!--            {{form}}-->
<!--        </form>-->

        <form action="qq.html" method="get">
            {% csrf_token %}
            {{form.as_p}}
            <input type="button" value="ثبت نام">
        </form>
    </div>
{% endblock %}

templates/formTest/form1.html
{% extends 'maintemplate.html' %}

{% block content %}
    <h4 class="blog-title"> آموزش کار با فرمها</h4>
    <div class="form-box">
            <form action="" method="get">
                {% csrf_token %}
                <div>
                    <label for="name">نام : </label>
                    <input type="text" id = "name" name="fname">
                </div>
                <div>
                    <label for="family">فامیلی : </label>
                    <input type="text" id = "family" name="lname">
                </div>
                <div>
                    <label for="name">سن : </label>
                    <input type="number" id = "age" name="age">
                </div>
                <div>
                    <input type="submit" value="ثبت نام">
                </div>
            </form>
    </div>
{% endblock %}

templates/formTest/form2.html
{% extends 'maintemplate.html' %}

{% block content %}
    <h4 class="blog-title"> آموزش کار با فرمها</h4>
    <div class="form-box">
            <form action="" method="get">
                {% csrf_token %}
                <div>
                    <label for="id_name"> نام:</label>
                    {{form.name}}

                </div>
                <div>
                     <label for="id_family"> نام خانوادگی:</label>
                    {{form.family}}
                </div>
                <div>
                     <label for="id_age">سن :</label>
                    {{form.age}}
                </div>
                <div>
                     <label for="id_is_active"> فعال/غیرفعال:</label>
                    {{form.is_active}}
                </div>
                <div>
                    <input type="submit" value="ثبت نام">
                </div>
            </form>
    </div>
{% endblock %}

templates/formTest/form3.html
{% extends 'maintemplate.html' %}

{% block content %}
    <h4 class="blog-title"> آموزش کار با فرمها</h4>
    <div class="form-box">
<!--        <form action="">-->
<!--            {% csrf_token %}-->
<!--            {{form}}-->
<!--        </form>-->

        <form action="hatm.html" method="">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="ثبت نام">
        </form>
    </div>
{% endblock %}

templates/formTest/form4.html
{% extends 'maintemplate.html' %}

{% block content %}
<h4 class="blog-title"> آموزش کار با فرمها</h4>
<div class="form-box">
    <form action="hatm.html" method="get">
        {% csrf_token %}
        <table STYLE="margin:10px">
            <tr>
                {{form.as_table}}
             </tr>
        </table>
        <input type="submit" value="ثبت نام">
    </form>
</div>
{% endblock %}

templates/formTest/form5.html
{% extends 'maintemplate.html' %}

{% block content %}
    <h4 class="blog-title"> آموزش کار با فرمها</h4>

    {% if form.errors %}
    <div style="height:100px; width:60%; margin:10px auto; background-color: #a13232;">
        <ul style="text-align: right">
            {% for error,message in form.errors.items %}
                <li>{{message}}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}


    <div class="form-box">
        <form action="" method="post" >
            {% csrf_token %}
            <table>
                {{form.as_table}}
                <tr>
                    <td colspan="2">
                        <input type="submit" value="ثبت نام">
                    </td>
                 </tr>
            </table>
        </form>
    </div>
{% endblock %}

templates/formTest/form6.html
{% extends 'maintemplate.html' %}

{% block content %}
    <h4 class="blog-title"> آموزش کار با فرمها</h4>

    {% if form.errors %}
    <div style="height:100px; width:60%; margin:10px auto; background-color: #a13232;">
        <ul style="text-align: right">
            {% for error,message in form.errors.items %}
                <li>{{message}}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}


    <div class="form-box">
        <form action="" method="post" >
            {% csrf_token %}
            <table>
                {{forms_set.as_table}}
                <tr>
                    <td colspan="2">
                        <input type="submit" value="ثبت نام">
                    </td>
                 </tr>
            </table>
        </form>
    </div>
{% endblock %}

templates/formTest/form7.html
{% extends 'maintemplate.html' %}

{% block content %}
<h4 class="blog-title"> آموزش کار با فرمها</h4>

{% if form.errors %}
<div style="height:100px; width:60%; margin:10px auto; background-color: #a13232;">
    <ul style="text-align: right">
        {% for error,message in form.errors.items %}
        <li>{{message}}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}


<div class="form-box">
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <th>{{form.as_table}}</th>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" value="ثبت نام">
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

templates/formTest/index.html
{% extends 'maintemplate.html' %}

{% block content %}
<h4 class="blog-title"> آموزش کار با فرمها</h4>
    {% for post in posts %}
        <div>
            <h2>{{post.title}}</h2>
            <p>{{post.description}}</p>
        </div>
    {% endfor %}

{% endblock %}